### ISSUE TITLE
ZoomIn seems to cut off mask

### ISSUE THREAD

**Issue by nathantew14** [saic-vul/fbrs_interactive_segmentation#29]
In the paper, it was stated that ZoomIn draws a rectangle around the mask produced after a certain number of clicks. However, it seems to abruptly cut off the mask that would otherwise have continued. Is this expected behaviour? Thanks.

![screenshot](https://user-images.githubusercontent.com/40333518/100969225-bd62ac80-356d-11eb-83a8-cad6de426dfb.png)

**Comment by ptrvilya** [comment]
Hi! This is an expected behaviour as the Zoom-In activates right after the first click ("Skip clicks"=1) and crops the image around expanded mask with "Expand ratio"=1.4. So the mask wouldn't continue over the current borders as it stops exactly at the end of the crop that is passed to the network. If you increase "Skip clicks" the Zoom-In would presumably be initialized with a better mask and this cut off wouldn.t happen.

**Comment by nathantew14** [comment]
> Hi! This is an expected behaviour as the Zoom-In activates right after the first click ("Skip clicks"=1) and crops the image around expanded mask with "Expand ratio"=1.4. So the mask wouldn't continue over the current borders as it stops exactly at the end of the crop that is passed to the network. If you increase "Skip clicks" the Zoom-In would presumably be initialized with a better mask and this cut off wouldn.t happen.

Hi, thanks for the reply. I was wondering if this would work much better then if a clicking strategy similar to DEXTR's (clicks at extreme regions of the object) is used, which would ensure that masks are never cut off by ZoomIn?

**Comment by ptrvilya** [comment]
In most cases we observe better performance and as I said if you increase the 'Skip clicks' even to 2 you would get a better bbox after just 2 clicks. DEXTR's strategy requires strictly 4 clicks as an input and doesn't support corrections (even though there's a paper that suggests a  mixed input: extreme points and clicks), so I believe that for f-BRS method clicks input is a better choice.
