### ISSUE TITLE
get oom error

### ISSUE THREAD

**Issue by lfxx** [saic-vul/fbrs_interactive_segmentation#37]
When i do inference in loop,gpu memory usage is growing continually which leads to oom error at last.How to resolve this problem?thank you!

**Comment by ksofiyuk** [comment]
It occurs due to the not very memory efficient GPU implementation of the DistMaps operator (memory consumption increases linearly with the number of clicks). However, we provide the memory and computational efficient implementation of this operator for the CPU. You can set `cpu_dist_maps=True` in the model to force using the CPU for this operator.
