### ISSUE TITLE
controls missing in mac os

### ISSUE THREAD

**Issue by sjf18** [saic-vul/fbrs_interactive_segmentation#7]
hi, thanks for your great work.
i found some controls cant be used in mac os, only left mouse button can be used for positive clicks, other controls are all missing

**Comment by ptrvilya** [comment]
Hi, we have tested GUI on Ubuntu 18.04 with tkinter.TkVersion 8.6. Problems on MacOS may encounter due to issues with Apple-supplied Tcl/Tk (refer to https://www.python.org/download/mac/tcltk/). Unfortunately we don't support MacOS, so if you are unable to solve this issue please consider using docker for the demo.
